name = "Kepler"
uuid = "adce7ac5-41de-41eb-81d7-62287823a1c6"
version = "0.2.0"
authors = ["Samuel Cornwall"]

[deps]
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SPICE = "5bab7191-041a-5c2e-a744-024b9c3a5062"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DiffResults = "1.1.0"
Enzyme = "0.13.48"
ForwardDiff = "0.10.38"
LinearAlgebra = "1.11.0"
Printf = "1.11.0"
Roots = "2.2.5"
SPICE = "0.2.3"
StaticArrays = "1.9.15"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
